### ISSUE TITLE
With 1.13.11 : "alter advancement" does not work anymore ?

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#77] opened 2018-02-14 11:35 UTC
Wesnoth version : latest commit from "git log"   (edited : try to clarifiy the version used )
commit 0bc03e14c749699b7dfee5e8921b8ac34cf49d58
Date:   Tue Feb 13 16:19:22 2018 +1100

Loti : latest commit from git :
commit b2019140e9ee3b034c230a133c6600c4ff1cc8ae
Author: Dugy 
Date:   Wed Jan 31 22:19:15 2018 +0100

I tried with various units, and it always gives the same messge (on screen and in logs)
Invalid WML found: Attempt to store nonexistent unit type 'Advancing Efraim_lich'.
Invalid WML found: Attempt to store nonexistent unit type 'Advancing Lethalia_lich'.
Invalid WML found: Attempt to store nonexistent unit type 'Advancing Dwarvish Hero'.
Invalid WML found: Attempt to store nonexistent unit type 'Advancing Delly_lich'.

[LotI1-First Confrontation Tour 9-cannot-alter-advancement.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1723759/LotI1-First.Confrontation.Tour.9-cannot-alter-advancement.gz)

I am pretty sure that it did work recently (1.13.10+ january).

**Comment by Dugy** [comment] 2018-02-14 11:47
I am pretty sure that the commit from Charles Dang didn't break it.

The _Invalid WML found_ errors look relevant and disturbing weird. I will check it out.

**Comment by alain-bkr** [comment] 2018-02-14 15:38
I tried to reduce the search scope, but it is too complicted for me : 
* i loaded a saved game in 1.13.10+ with 1.13.11 , i got a message , the game was loaded , and all the games of this playing sessions behave ccorectly, i can reload them and alter_advancement.

* the next day i loaded my most recent game in 1.13.11 and played , and noticed the bug with alter_advancement. None of this game accept alter_advancemement.

* I put options> advanced > debug > wml  to max debug info, this gives the following messages : 

20180214 16:29:07 info wml: helper.set_wml_tag_metatable has been deprecated indefinitely.
   (Note: You should use wml.tag instead in new code)
20180214 16:29:17 info wml: helper.shallow_literal has been deprecated indefinitely.
   (Note: You should use wml.shallow_literal instead in new code)
20180214 16:29:17 info wml: helper.get_child has been deprecated indefinitely.
   (Note: You should use wml.get_child instead in new code)
20180214 16:29:17 info wml: wesnoth.set_variable has been deprecated indefinitely.
   (Note: You should use wml.variable.set instead in new code)
Invalid WML found: Attempt to store nonexistent unit type 'Advancing Efraim_lich'.

**Comment by Dugy** [comment] 2018-02-14 15:48
Those other reports are irrelevant. The problem is that some unit types are not loaded. It's lucky that the game doesn't outright throw you back to main menu with an exception. It seems it is somehow unable to read the {GENERIC_AMLA} and similar macros in some unit type files.

**Comment by alain-bkr** [comment] 2018-02-15 17:02
A similar message occured , when one unit should have levelup during opponent's turn betwenn turn 14 and 15 .

20180215 17:47:41 error scripting/lua: game_error: unknown unit type: Advancing Elvish Juggernaut
stack traceback:
	[C]: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml-flow.lua:52: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml-flow.lua:38: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml-flow.lua:6: in function <lua/wml-flow.lua:5>
	[C]: in field 'fire_event'
	lua/wml-tags.lua:164: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml-flow.lua:52: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml-flow.lua:20: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml-flow.lua:6: in function <lua/wml-flow.lua:5>

[LotI1-Chasing Dragons-Sauvegarde automatique14.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1728603/LotI1-Chasing.Dragons-Sauvegarde.automatique14.gz)

[LotI1-Chasing Dragons-Sauvegarde automatique15.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1728602/LotI1-Chasing.Dragons-Sauvegarde.automatique15.gz)

**Comment by Dugy** [comment] 2018-02-15 17:38
It just confirms that some unit types are not loaded.

**Comment by alain-bkr** [comment] 2018-02-16 10:58
OK, thanks for the explanations.

All the messages on screen are really annoying.
Is there a way to only have them only in the console output and not on screen ?

![2018-02-15_23-28-48__advancing_juggernaut](https://user-images.githubusercontent.com/31039036/36304613-8b70ed86-1310-11e8-95b6-737b355be1ad.png)

**Comment by Dugy** [comment] 2018-02-16 12:14
You can hide them with Ctrl+X if I recall correctly, they shouldn't pop out too often.

**Comment by alain-bkr** [comment] 2018-02-18 18:04
comment from the wesnot issue  https://github.com/wesnoth/wesnoth/issues/2514

this was likely broken by 13a4822 but actually this should really be fixed in the addons code.
--

**Comment by Dugy** [comment] 2018-02-18 18:07
I see. Now the unit types are referenced somewhere as Advancing Something, elsewhere as AdvancingSomething and it doesn't fit together.

**Comment by Dugy** [comment] 2018-02-18 19:00
It should be fixed now with 661223b, but I could not test it - current revision of wesnoth 1.13 does not compile because of some inconsistencies while porting to C++11.

**Comment by Vultraz** [comment] 2018-02-18 21:02
You could have also fixed the code by simply wrapping the value in quotes. Ie,
> `type="Advancing $unit.type"`

You were relying on buggy behavior in the WML parser before, where WML key values with variable substitution would lose the space before the variable name. I fixed that.

As for compilation, if you have a build issue, please report it on the Wesnoth issues page.

**Comment by Dugy** [comment] 2018-02-18 21:09
No, it would _not_ have fixed it. It was creating unit types without the break (it was macro substitution) and using them in a variable substitution with a break (the break was ignored because there were no quotation marks), so it was adapted to the 'bugged' version.

**Comment by Vultraz** [comment] 2018-02-18 21:13
I edited my comment after I spotted my error. Sorry, just woke up.

The gist of it is you were relying on the string with a space being parsed as having no spaces. You can either solve it as you did, by manually deleting the space, or by ensuring there is a space in the unit type ID. Though perhaps a better fix would be to use underscores in both cases. Ie, `Advancing_Lich_Efriem`.

**Comment by Dugy** [comment] 2018-02-18 21:40
I have tested that the bug is gone now.

I have not inserted those underscores because it would cause this bug to manifest in all mid-scenario save files. Also, the type has such an odd name because it's only a way to store data outside save files, the unit is never played with (unless there's an error) and needs to have an odd name to make it visible.

As for the wesnoth compilation error, it's fixed already. I was lazy to write a bug report because it would be spotted very fast anyway.

**Closed by Dugy** 2018-02-18 21:40 UTC
