### ISSUE TITLE
Crafting a weapon does not work on Reaper

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#209] opened 2019-01-02 20:04 UTC
[LotI2-The Gates of Hell-Auto-Save1.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2721882/LotI2-The.Gates.of.Hell-Auto-Save1.gz)

Select the Reaper and go into the crafting menu
Select weapon, note that there are no options to craft

**Comment by arobinson** [comment] 2019-01-02 20:05
Seems to be broken for all units acutally

**Comment by Dugy** [comment] 2019-01-02 20:07
What OS are you using?

It seems that a commit that fixes a problem for one person breaks it for another.

**Comment by arobinson** [comment] 2019-01-02 20:12
Mac OSX High Sierra
![screen shot 2019-01-02 at 1 11 53 pm](https://user-images.githubusercontent.com/93213/50610381-fda3e680-0e8f-11e9-96d9-476187ec7731.png)

**Comment by arobinson** [comment] 2019-01-02 20:31
Note that resizing the window causes the contents to re-appear

**Comment by Dugy** [comment] 2019-01-02 20:43
It's a duplicate of #206 , but it has some useful information.

**Closed** 2019-01-06 12:58 UTC
