### ISSUE TITLE
LotI's heal_unit errors

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#828] opened 2024-07-18 23:08 UTC
Forum user reports all recalls missing in Toxic Sun.

```
20240718 21:30:34 warning engine: Invalid anchor!
20240718 21:30:34 warning engine: Invalid anchor!
20240718 21:30:37 error deprecation: helper.lua ist veraltet und wird in Version 1.19.0 entfernt.; Everything in this module has been moved into the core modules
20240718 21:30:38 error scripting/lua: ~add-ons/Legend_of_the_Invincibles/lua/hacks.lua:95: attempt to index a nil value (local 'cfg')
stack traceback:
~add-ons/Legend_of_the_Invincibles/lua/hacks.lua:95: in upvalue 'old_heal_unit'
~add-ons/LotI_Era/lua/hacks.lua:102: in local 'cmd'
lua/wml-utils.lua:145: in field 'handle_event_commands'
lua/wml-flow.lua:206: in local 'cmd'
lua/wml-utils.lua:145: in field 'handle_event_commands'
lua/wml-flow.lua:5: in function <lua/wml-flow.lua:4>
```

I'm suspecting LotI Era is (not) doing something, and/or there's an issue with the new(?) heal_unit check for unhealable.  Either way, it might make sense to add a check that cfg exists, even if not LotI's fault.

https://forums.wesnoth.org/viewtopic.php?p=691899#p691899

P.S.

`active_mods="Campaign_Hardcoreifier,Dead_Bodies,Gui Debug Tools,LotI_Era,RandomRecruits,reflection,ROLAdvancement_Modification,wind_modification,bonus_tile,Campaign_Steppeifier,Bloody_Mod_PSR,Campaign_EoMaifier,load_alt_themes"`

**Comment by Dugy** [comment] 2024-07-19 00:35
I don't understand what exactly happened, but that error happened in a prestart event of that scenario that was supposed to heal all units stored previously and place them on the recall list, because you were swapping leaders there. The lua crash has paused the execution of the event, so the units were not put on the recall list.

However, I think that the patched `[heal_unit]` works also in a prestart event. So it's probably something has caused the old `[heal_unit]` to be `nil` at that point, and I don't know what could be doing that. If you can't replicate this in your own save file, it's caused by an interplay of add-ons, in which case I would close this as not going to work on and ask him to disable add-ons until it works and he finds which one caused it.

**Comment by Dugy** [comment] 2024-07-19 00:42
If it's indeed the `Loti Era` (why on Earth would anyone use this campaign while using this campaign), then it's probably related to having performed some actions twice that were not meant to be performed twice. I don't know if it causes `[heal_unit]` to be broken only in prestart or if it's everywhere.

**Comment by white-haired-uncle** [comment] 2024-07-19 00:43
Actually, I think it might be this:

`cfg = cfg.__parsed`

It looks like LotI Era just copies the same exact wesnoth.wml_actions.heal_unit(cfg).

Any idea what might make that be nil?

Actually, if Loti_Era's heal_unit does `cfg = cfg.__parsed`, and then calls LotI's heal_unit, then would could cfg be nil at that point (after the second iteration of __parsed)?  Because that makes sense, and matches the stack flow perfectly.

**Comment by white-haired-uncle** [comment] 2024-07-19 00:46
Put another way, I think Loti_Era is inserting itself such that since both try to do `cfg = cfg.__parsed`, the result is effectively
`cfg = original_cfg.__parsed.__parsed`

**Comment by Dugy** [comment] 2024-07-19 00:49
Aha... yeah. The `cfg` variable is not a lua table, but a special object that has a special field `__parsed`, which will give you a lua table when you access it. If you do it once, you get a lua table from a special object, if you do it twice, you get a `__parsed` field of a lua table, but since there is no such setting there, it's `nil`.

I think it should be fixable by erasing that line and changing the next line to `if cfg.__parsed.respect_unhealable == false then`.

**Comment by white-haired-uncle** [comment] 2024-07-19 01:13
I reported it on the Loti_Era thread.

https://forums.wesnoth.org/viewtopic.php?p=691905#p691905

I think checking for __parsed == nil would be more robust, but it's really really unlikely to happen and it's not really a fix anyway.  Most you can do, IMO, is just throw a "This shouldn't happen".

I'm going to close this and come back to it if it turns out I'm wrong.

I really wonder if it makes any sense to run Loti_Era while playing LotI in the first place, but then I've never even looked at mods.

**Closed** 2024-07-19 01:17 UTC

**Comment by white-haired-uncle** [comment] 2024-07-19 05:00
Now that I think of it, if wesnoth's [heal_unit] will take a table as input, then LotI's probably should too.

**Comment by Dugy** [comment] 2024-07-23 08:21
The problem is that the patched `[heal_unit]` adds a new part to the filter, which requires manipulating WML, which is something that the original `[heal_unit]` doesn't do.

I have changed the code to check what is the type and call the `__parsed` only when needed, but this felt like maintaining another person's add-on.
