### ISSUE TITLE
 Philip cannot equip crossbow

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#234] opened 2019-01-20 07:23 UTC
The special unit Philip  cannot take a crossbow at this moment : 

[LotI2-Misguiding Lives Tour 1_philip_crossbow_or_not.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2776349/LotI2-Misguiding.Lives.Tour.1_philip_crossbow_or_not.gz)

but later it can , he is geared with it now : 
[LotI2-Axadria Tour 1.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2776350/LotI2-Axadria.Tour.1.gz)

**Comment by Dugy** [comment] 2019-01-20 11:46
Duplicate of #235

**Closed by Dugy** 2019-01-20 11:46 UTC

**Comment by Dugy** [comment] 2019-01-20 16:07
Phillip's initial advancements have two effects - new unit type and a selected upgrade. The new unit type is always the same, but the upgrade is selectable. It made it a bit confusing, but the base type does not have the attack. You can check it for yourself.

I don't blame you for not seeing the two problems have an identical underlying cause.
