### ISSUE TITLE
Some AIs take quite long to move

### ISSUE THREAD

**Issue by Discontinuum** [Dugy/Legend_of_the_Invincibles#401] opened 2022-01-14 23:29 UTC
For example allied Argan in Sightseeing, sea creatures in The Infinite Legion

**Comment by Discontinuum** [comment] 2022-01-24 15:23
[LotI1-Journey South Turn 17.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/7926574/LotI1-Journey.South.Turn.17.gz)
Here allied AI of Necromancer, after his female necromancer opponent fled and her troops destroyed, freezes the game sooo hard, so I had to kill all his units with debug to continue the game

**Comment by Dugy** [comment] 2022-02-10 08:45
I removed all custom AI and campaign events from it and the problem is still there. Looks like an AI bug.

I reported it here: https://github.com/wesnoth/wesnoth/issues/6504

**Comment by Discontinuum** [comment] 2022-02-10 22:04
Well, in the bug in Wesnoth you said it's always about allied sides but in The Infinite Legion it's about Water Creatures team which is allied to nobody. The most amazing here is that the side with 6 units freezes the game hard but the size with 195 units works fast... (I play with skip ai moves btw)
[LotI1-Infinite Legion-Auto-Save1.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/8044632/LotI1-Infinite.Legion-Auto-Save1.gz)

**Comment by Dugy** [comment] 2022-06-29 07:52
It was found to be an inefficiency in the Micro AI. The problem was that in absence of enemy leaders, the units resort to highly inefficient action calculations. Setting enemy units as explicit targets was identified as a workaround.

I have committed the workaround before the fix comes.

**Closed by Dugy** 2022-06-29 07:52 UTC
