### ISSUE TITLE
Kamikaze sprint does not work properly

### ISSUE THREAD

**Issue by arodiss** [Dugy/Legend_of_the_Invincibles#13] opened 2017-03-24 12:41 UTC
First of all thank you for creating (and supporting!) this awesome piece of campaign.

Though it's really great, I noticed that "kamikaze sprint" does not work properly. I tried it couple of times in different situations, and result is always the same.
First, it never kills any of the victims - it can reduce someone to negative HP, but attackees are still there
Secondly, after using this attack *attacker himself disappears*. Well, this might be sort of intended, word "kamikaze" suggests something like this - but suicide is not mentioned explicitly neither in ability nor in weapon description. BTW, if this is really intended, IMO in addition to proper description thing should be significantly powered up - sacrificing advanced unit with an item is a big deal.

LoTI 3.1.23, Wesnoth 1.12.5

**Comment by Dugy** [comment] 2017-03-25 21:08
I was able to replicate the problem. I have not found the cause yet.

**Comment by Dugy** [comment] 2017-03-27 06:27
I have fixed it.

I am have another change half-committed, so I am not committing the fix yet. It will be a part of the soonest update.

**Comment by arodiss** [comment] 2017-04-03 05:38
@Dugy 
Do you want me to test and close this?

**Comment by Dugy** [comment] 2017-04-03 05:48
Leave it open.

**Closed** 2017-09-12 11:03 UTC
