### ISSUE TITLE
Magical, guided, but not both

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#713] opened 2024-03-25 22:54 UTC
I gave Tears of Void to a druid.  She now has an aim attack which always has a 70% chance to hit.  It also always has a 90% chance to hit.

**Comment by Dugy** [comment] 2024-03-25 23:06
How do they stack? Magical specifically means that the chance to hit is overriden to be 70%, guided is the same but 90%, so the engine will pick one.

**Comment by white-haired-uncle** [comment] 2024-03-25 23:09
During combat it shows 90%.

**Comment by Dugy** [comment] 2024-03-25 23:11
That is the expected behaviour. Guided is applied later, so it overrides the previous one.

**Comment by white-haired-uncle** [comment] 2024-03-25 23:13
The issue is the attack description.  It says both, which can't be true.

**Comment by Dugy** [comment] 2024-03-25 23:25
That's how the game works. If I wrote code to remove those specials that were overriden, it would feel weird to someone else.

**Comment by white-haired-uncle** [comment] 2024-03-26 02:00
Well, she didn't have an aim attack until she picked up the ToV so it's not like it would really be removing anything.

And I think in the general case, no one's going to wonder why magical doesn't show up when guided (better) does, but they might wonder how they can have both.

**Comment by Dugy** [comment] 2024-03-27 09:47
I don't understand your point now. He could she pick up ToV and get both magical and guided from it? It only grants guided.

**Comment by white-haired-uncle** [comment] 2024-03-27 12:16
I assume it was inherited/cloned somehow from her thorns attack, since aim shares the weapon specials and damage type with it.  I took ToV off her and gave it to a Seer and now it's an arcane attack for the Seer.

FWIW, the druid was holding ToV when she advanced to FI, and now aim has poison as well.

First Shyde in the recall list.  Quirimea
[LotI1-The Beginning.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/14773073/LotI1-The.Beginning.gz)

**Comment by white-haired-uncle** [comment] 2024-03-30 03:44
I've never really seen any use for 'aim'.  Probably because I can't remember ever giving it to a unit with a ranged attack that wasn't magical, and the difference between magical and guided isn't enough to offset the damage loss (and they're the same type, so no help there).

**Comment by Dugy** [comment] 2024-03-30 10:04
It gives a 28% increased chance to hit, so it does offset the damage loss. But only by a small margin, which would mean that other amulets are probably better. So it would make sense to give it some additional bonus.

**Comment by white-haired-uncle** [comment] 2024-03-30 13:01
I think it's 20% to hit (vs magic), -20% damage, which is almost a wash unless the enemy has very small HP or you're trying to poison/slow/etc.  I don't mind items that don't seem to do much, or do as much as they could, but it seems if you wanted it to have a bonus it would use a different damage type (lightning?).

BTW, in item_list.cfg, we see things like this:

```
        damage=-50
        {QUANTITY damage -30 -40 -50}
        attacks=80
        {QUANTITY attacks 100 80 60}
```
Seems redundant, wondering if there's a reason for it.   Don't care, just curious.

USUALLY, the (unused?) attribute matches the value for hard, though in the above one of them doesn't.  That one, BTW, is from Relentless Fury, which bugs me because I can't figure out why the gui says "80 more attacks" instead of "80% more".

**Comment by Dugy** [comment] 2024-03-30 15:42
> I think it's 20% to hit (vs magic)

Wrong. Increasing a 70% chance to 90% chance means a 28% increased chance, because 0.7 * 1.2857 = 0.9.

If you still don't believe me, consider this:

* 10-5 attack, 70% chance -> 35 damage in average
* 10-5 attack, 90% chance -> 45 damage in average (which is 28% more than 35)

> Seems redundant, wondering if there's a reason for it. Don't care, just curious.
You don't always have the EASY, NORMAL and HARD definitions, for example in multiplayer. Therefore, there has to be a default value for cases where neither of these is defined.

**Comment by white-haired-uncle** [comment] 2024-04-06 03:15
Um, I gave Lethalia Tears of the Void.  Granted, her ff attack does less damage (16x5 vs 20x5), but it still kind of crazy.  aim needs a new damage type (I'm loading her up with arcane for ff, so it would be nice if that didn't effect aim).

**Comment by Dugy** [comment] 2024-04-07 12:23
Wait, you were first telling it's next to useless and now you're telling it's overpowered?

**Comment by white-haired-uncle** [comment] 2024-04-07 13:03
I still think it is, but I found a case where it is "too powerful".  Either way, I think it should work differently.

I think the difference is the amount of damage she does.  Once you get to the point that you're going to kill pretty much any unit you attack, extra damage is wasted.  So in this case, the differences is she goes from killing _most_ units to killing _almost every_ unit.  I think it'd be more fun if she actually missed once in a while.

**Comment by Dugy** [comment] 2024-04-07 13:30
It's better than nothing, and it has a niche use where it's exactly what you need. That is fine in my opinion.

**Comment by white-haired-uncle** [comment] 2024-04-09 20:04
Found the niche.  Shamans and mages.  Both are fragile.  The extra chance to hit is quite helpful trying to attain L2.  Often I'll use one to attack a severely injured foe to grab XP, knowing on the off chance it misses completely .it's probably going to die on the AI turn.

**Comment by Dugy** [comment] 2024-04-09 20:05
May I close this now?

**Comment by white-haired-uncle** [comment] 2024-04-09 21:15
Sure.  But I still think it looks bad to have magical and guided both appear in the weapon specials.

**Comment by Dugy** [comment] 2024-04-09 22:47
There is no good mechanism to remove the overriden weapon special except by writing code to handle this specific case.

**Closed by Dugy** 2024-04-09 22:47 UTC

**Comment by white-haired-uncle** [comment] 2024-05-25 05:33
Ran into this.  It's picking only the best backstab special when multiple apply.  Without really looking at it right now, this could be a template for picking only the best weapon accuracy when multiple apply.

 https://github.com/Dugy/Legend_of_the_Invincibles/blob/9865c22ed30f91094d02791376512da160cd4a44/lua/stats.lua#L572-L590
